config/routes.rb
Rails.application.routes.draw do
  resources :tools
  resources :users, only: [:index, :new, :create, :show]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#new'
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/tool.rb
class Tool < ActiveRecord::Base
  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :tools
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :most_recent_tool, :current_user
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def most_recent_tool
    if Tool.exists?(cookies[:most_recent_tool_id].to_i)
      Tool.find(cookies[:most_recent_tool_id].to_i).name
    else
      "No recent tools"
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])

    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to :login_path
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  def index
    @tools = current_user.tools
  end


  def show
    @tool = Tool.find(params[:id])
    cookies[:most_recent_tool_id] = @tool.id
  end

  def new
    @tool = Tool.new
  end

  def create
    @user = current_user
    @tool = @user.tools.new(tool_params)

    if @tool.save
      redirect_to tool_path(@tool.id)
      flash[:notice] = "Tool created!"
    else
      flash[:error] = @tool.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @tool = Tool.find(params[:id])
  end

  def update
    @tool = Tool.find(params[:id])
    if @tool.update(tool_params)
      redirect_to tool_path(@tool.id)
    else
      render :edit
    end
  end

  def destroy
    tool = Tool.find(params[:id])
    tool.destroy
    redirect_to tools_path
  end

  private

  def tool_params
    params.require(:tool).permit(:name, :price, :quantity, :category_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
   @user = User.new(user_params)
   if @user.save
     session[:user_id] = @user.id
     redirect_to @user
   else
     flash.now[:error] = @user.errors.full_messages.join(", ")
     render :new
   end
 end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToolChest</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
<body>

<% flash.each do |type, msg| %>
  <%= content_tag :div, msg, class: "flash_#{type}" %>
<% end %>

<p>
  <strong>Newest tool:</strong> <%= most_recent_tool %>
</p>

<% if current_user %>
  Welcome, <%= current_user.username %>.
  <%= link_to "Logout", logout_path, method: :delete %>
<% else %>
  <%= link_to "Login", login_path %>
<% end %>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/tools/_form.html.erb
<%= form_for  tool do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.label :quantity %>
  <%= f.text_field :quantity %>
  <%= f.collection_select(:category_id, Category.order(:name), :id, :name, include_blank: true) %>

  <%= f.submit %>
<% end %>

app/views/tools/edit.html.erb
<%= render partial: "form", locals: {tool: @tool} %>

app/views/tools/index.html.erb
<h1>All Tools</h1>

<%= link_to "Create New Tool", new_tool_path %>
<% @tools.each do |tool| %>
  <p><%= link_to "#{tool.name}", tool_path(tool.id) %> - <%= tool.quantity %></p>
<% end %>

app/views/tools/new.html.erb
<%= render partial: "form", locals: {tool: @tool} %>

app/views/tools/show.html.erb
<div class="tool_info">
  <h2><%= @tool.name %> - <%= @tool.quantity %></h2>
  <h3>Price <%= @tool.price.to_f %></h3>
</div>
<%= link_to "Edit", edit_tool_path %>
<%= link_to "Delete", tool_path(@tool.id), method: :delete %>
<%= link_to "Tools Index", tools_path %>

app/views/users/index.html.erb
<h1>Your Tools</h1>

app/views/users/new.html.erb
<h1>Create a New Account</h1>

<%= form_for(@user) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<%= link_to "Tools", tools_path %>